# Generated by Django 2.0.1 on 2018-02-04 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180204_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='width_field',
        ),
        migrations.AddField(
            model_name='comment',
            name='model_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
